apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001"
  labels:
     release: stable 
spec:
  capacity:
    storage: "8Gi" 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-071c9372d1aeb7f92" 
