scrape_configs:
    - job_name: 'kubelet'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
              ca_file: /etc/kubernetes/pki/ca.crt
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['192.168.99.100:32727']
